### PR TITLE
Fix owner for directory /opt/hivemq/backup

### PR DESCRIPTION
**Pull request by hertfelder**
Owner of directory ```/opt/hivemq/backup``` was ```root:root```. This caused a triggered backup to fail with error message

> ERROR - Could not write retained messages into xml: Unable to create directory /opt/hivemq/backup/...

Fixed owner to ```hivemq:hivemq``` in ```docker-entrypoint.sh```.

### CODE REVIEW

**Comment by fraschbi** [comment]
@cla-bot check

**Comment by fraschbi** [comment]
Hi @hertfelder,

Thanks a lot for the PR. I would love to merge it.
Can you please fill out our  CLA (see the [Contribution Guide](https://github.com/hivemq/hivemq-community/blob/master/CONTRIBUTING.adoc)) so I can do that?

Kind regards,
Florian

**Comment by fraschbi** [comment]
After talking to @hertfelder I created a PR myself with these changes, due to time constraints on CLA clarification.
Thank you again for the input!

**Comment by hertfelder** [comment]
Thanks!

**Pull request closed without merging**
